// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(WaterConsumptionDb))]
    [Migration("20221026125921_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("API.Models.WaterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Consumption")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 100,
                            DateTime = new DateTime(2022, 10, 1, 1, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Consumption = 110,
                            DateTime = new DateTime(2022, 10, 1, 1, 10, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Consumption = 120,
                            DateTime = new DateTime(2022, 10, 1, 1, 20, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Consumption = 130,
                            DateTime = new DateTime(2022, 10, 1, 1, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Consumption = 140,
                            DateTime = new DateTime(2022, 10, 1, 1, 40, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Consumption = 150,
                            DateTime = new DateTime(2022, 10, 1, 1, 50, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Consumption = 100,
                            DateTime = new DateTime(2022, 10, 1, 2, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Consumption = 110,
                            DateTime = new DateTime(2022, 10, 1, 2, 10, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Consumption = 120,
                            DateTime = new DateTime(2022, 10, 1, 2, 20, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Consumption = 140,
                            DateTime = new DateTime(2022, 10, 1, 2, 40, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Consumption = 150,
                            DateTime = new DateTime(2022, 10, 1, 2, 50, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Consumption = 100,
                            DateTime = new DateTime(2022, 10, 1, 3, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Consumption = 110,
                            DateTime = new DateTime(2022, 10, 1, 3, 10, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Consumption = 120,
                            DateTime = new DateTime(2022, 10, 1, 3, 20, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Consumption = 130,
                            DateTime = new DateTime(2022, 10, 1, 3, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Consumption = 140,
                            DateTime = new DateTime(2022, 10, 1, 3, 40, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Consumption = 150,
                            DateTime = new DateTime(2022, 10, 1, 3, 50, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Consumption = 100,
                            DateTime = new DateTime(2022, 10, 1, 4, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Consumption = 110,
                            DateTime = new DateTime(2022, 10, 1, 4, 10, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 20,
                            Consumption = 120,
                            DateTime = new DateTime(2022, 10, 1, 4, 20, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 21,
                            Consumption = 130,
                            DateTime = new DateTime(2022, 10, 1, 4, 30, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 22,
                            Consumption = 140,
                            DateTime = new DateTime(2022, 10, 1, 4, 40, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 23,
                            Consumption = 150,
                            DateTime = new DateTime(2022, 10, 1, 4, 50, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
